---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Values.infrastructure.volumeName }}-persistent-storage"
  namespace: "{{ .Values.infrastructure.namespace }}"
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: {{ .Values.resources.volume.storageClass }}
  resources:
    requests:
      storage: {{ .Values.resources.volume.size }}